"""Recreate vendor/rav1d from the published rav1d crate.

Why a copy exists: rav1d exposes the dav1d C interface as `extern "C"`
functions. In Rust a panic that reaches an `extern "C"` function cannot unwind;
the process is aborted, and `catch_unwind` cannot stop it. rav1d does panic on
damaged input (its error path unwraps a missing frame header), so a corrupt AVIF
file would close the viewer. The only change made here is to declare every
`extern "C"` item as `extern "C-unwind"`, so that Kova Image can catch such a
panic around the decoder and report the file as damaged.

Everything else is the published source, minus what Kova Image does not use:
the assembly routines (the `asm` feature stays off), the build script that
assembles them, the C-only files and the crate's own profile settings. Run this
again after changing the version in Cargo.toml, then review `git diff`.

Usage: python scripts/vendor-rav1d.py [path to an unpacked rav1d crate]
"""
from pathlib import Path
import glob
import re
import shutil
import sys

VERSION = "1.1.0"
root = Path(__file__).resolve().parent.parent
target = root / "vendor/rav1d"

if len(sys.argv) > 1:
    source = Path(sys.argv[1])
else:
    candidates = glob.glob(str(Path.home() / f".cargo/registry/src/*/rav1d-{VERSION}"))
    if not candidates:
        raise SystemExit(f"rav1d {VERSION} is not in the cargo registry; run `cargo fetch`")
    source = Path(candidates[0])

if target.exists():
    shutil.rmtree(target)
(target / "src").mkdir(parents=True)
(target / "include").mkdir()

changed = 0
for tree in ("src", "include"):
    for path in sorted((source / tree).rglob("*.rs")):
        destination = target / path.relative_to(source)
        destination.parent.mkdir(parents=True, exist_ok=True)
        text = path.read_text(encoding="utf-8")
        patched, count = re.subn(r'extern "C"', 'extern "C-unwind"', text)
        changed += count
        destination.write_text(patched, encoding="utf-8", newline="\n")
lib = (source / "lib.rs").read_text(encoding="utf-8")
lib, count = re.subn(r'extern "C"', 'extern "C-unwind"', lib)
changed += count
# A path dependency reports its warnings, unlike a registry one. They are the
# upstream project's, not Kova Image's.
lib = "#![allow(warnings)]\n" + lib
(target / "lib.rs").write_text(lib, encoding="utf-8", newline="\n")
for name in ("COPYING", "README.md", "NEWS.dav1d"):
    if (source / name).exists():
        shutil.copy(source / name, target / name)

(target / "Cargo.toml").write_text(
    f'''# Generated by scripts/vendor-rav1d.py from rav1d {VERSION}; do not edit by hand.
[package]
name = "rav1d"
version = "{VERSION}"
edition = "2021"
rust-version = "1.79"
authors = ["Rav1d Developers", "Prossimo"]
description = "Rust port of the dav1d AV1 decoder, with C-unwind entry points (Kova Image copy)"
license = "BSD-2-Clause"
repository = "https://github.com/memorysafety/rav1d"
publish = false

[features]
# Kept so that the source's cfg(feature = "asm") conditions are known. Never enabled.
asm = []
asm_arm64_dotprod = ["asm"]
asm_arm64_i8mm = ["asm"]
asm_arm64_sve2 = ["asm"]
bitdepth_16 = []
bitdepth_8 = []

[lib]
name = "rav1d"
path = "lib.rs"

[dependencies]
assert_matches = "1.5.0"
atomig = {{ version = "0.4.0", features = ["derive"] }}
bitflags = "2.4.0"
cfg-if = "1.0.0"
libc = "0.2"
parking_lot = "0.12.2"
paste = "1.0.14"
raw-cpuid = "11.0.1"
strum = {{ version = "0.26", features = ["derive"] }}
to_method = "1.1.0"
zerocopy = {{ version = "0.7.32", features = ["derive"] }}
''',
    encoding="utf-8",
    newline="\n",
)
(target / "KOVA.md").write_text(
    f"""# rav1d {VERSION} as used by Kova Image

Published source of rav1d {VERSION} (BSD-2-Clause, see COPYING) with one change:
every `extern "C"` is declared `extern "C-unwind"`, so a panic inside the decoder
can be caught instead of aborting the process. The assembly routines, the build
script and the C-only files are left out. `scripts/vendor-rav1d.py` produces this
directory; comparing it with the published crate shows only that edit
({changed} occurrences) and `#![allow(warnings)]` in lib.rs.
""",
    encoding="utf-8",
    newline="\n",
)
print(f"{target}: {changed} extern \"C\" declarations changed")
